INSERT INTO PUBLIC.USERS (ID, LOGIN, PASSWORD) VALUES (1, 'moneta', '123');
INSERT INTO PUBLIC.USERS (ID, LOGIN, PASSWORD) VALUES (2, 'igorek', '123');
INSERT INTO PUBLIC.USER_ROLE (ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO PUBLIC.USER_ROLE (ID, NAME) VALUES (2, 'USER');
INSERT INTO PUBLIC.USER_ROLE (ID, NAME) VALUES (3, 'GUEST');
INSERT INTO PUBLIC.USERS_HAS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO PUBLIC.USERS_HAS_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO PUBLIC.USERS_HAS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
